import { ComboBox, Palette, Button, VerticalBox, ListView, AboutSlint, LineEdit, HorizontalBox, Spinner, StandardButton, ProgressIndicator, GridBox, StandardTableView, CheckBox } from "std-widgets.slint";

struct MatchedPattern {
    before: string,
    matched: string,
    after: string,
    partner: bool
}


export global AppState {
    in-out property <string> csv: "";
    in-out property <string> pdfs: "";
    in-out property <int> current-view: 0;

    in-out property <[string]> profiles;

    in-out property <string> profile;

    in-out property <[MatchedPattern]> csv-names;
    in-out property <[MatchedPattern]> pdf-names;

    in-out property <int> total_pdfs: 0;
    in-out property <int> total_buchungssaetze: 0;
    in-out property <int> linked: 0;

    in-out property <bool> instant-import: true;

    in-out property <string> mandantennummer;
}

component FileSelect inherits Rectangle  {
    callback request-pdf-dir();
    callback request-csv-file();
    callback get_names();
    callback change_profiles_location();
    callback delete_profile();

    VerticalBox {
        padding: 20px;

        Rectangle {
            border-radius: Platform.style-name == "fluent" ? 4px : 2px;
            border-width: Platform.style-name == "fluent" ? 2px : 1px;
            border-color: Palette.border;

            VerticalBox {
                padding: 20px;
                Text {
                    horizontal-alignment: center;
                    height:20px;
                    font-weight: 700;
                    text: "PDF Ordner: ";
                }
                Text {
                    height:20px;
                    text: AppState.pdfs;
                }
                Button {
                    height:30px;
                    text: "PDF Ordner wählen";
                    clicked => {
                        request-pdf-dir();
                    }
                }
            }
        }

        Rectangle {
            border-radius: Platform.style-name == "fluent" ? 4px : 2px;
            border-width: Platform.style-name == "fluent" ? 2px : 1px;
            border-color: Palette.border;

            VerticalBox {
                padding: 20px;
                Text {
                    horizontal-alignment: center;
                    height:20px;
                    font-weight: 700;
                    text: "Buchungsstapel: ";
                }
                Text {
                    height:20px;
                    text: AppState.csv;
                }
                Button {
                    height:30px;
                    text: "Buchungsstapel (.csv/.scs) wählen";
                    clicked => {
                        request-csv-file();
                    }
                }
            }
        }

        Rectangle {
            border-radius: Platform.style-name == "fluent" ? 4px : 2px;
            border-width: Platform.style-name == "fluent" ? 2px : 1px;
            border-color: Palette.border;
            VerticalBox {
                padding: 20px;
                Text {
                    height:20px;
                    text: "Mandant: ";
                }
                HorizontalBox {
                    ComboBox {
                        height:30px;
                        model: AppState.profiles;
                        current-index: 0;
                        selected(value) => {
                            AppState.profile = value
                        }
                    }
                    Button {
                        clicked => {delete_profile()}
                        icon: @image-url("./icons/delete.svg");
                    }
                    Button {
                        clicked => {change_profiles_location()}
                        icon: @image-url("./icons/settings.svg");
                    }
                }
            }
        }

        CheckBox {
            checked: AppState.instant-import;
            text: "Buchungsdaten direkt in SIMBA importieren";
        }
        Button {
            height: 30px;
            text: "Weiter";
            clicked => {
                root.get-names();
            }
        }
    }
}


component ChooseNamespace inherits Rectangle {
    callback filter(string);
    callback update_name(string);
    callback generate();
    callback update_ids(string);

    VerticalBox {
        padding: 0px;
        Rectangle {
            background: #EFF0F1;
            HorizontalBox {
                padding: 10px;
                Button {
                    clicked => {AppState.current-view = 0}
                    text: "Zurück";
                }

                LineEdit {
                    edited(text) => {filter(self.text)}
                    horizontal-alignment: TextHorizontalAlignment.center;
                    placeholder-text: "Filter";
                }
                ComboBox {
                    height:30px;
                    width: 200px;
                    model: ["Buchungstext", "Belegfeld 1", "Konto"];
                    current-index: 0;
                    selected(value) => {
                        update_ids(value)
                    }
                }
                LineEdit {
                    width: 200px;
                    edited(text) => {update_name(self.text)}
                    horizontal-alignment: TextHorizontalAlignment.center;
                    placeholder-text: "Mandant";
                }

                LineEdit {
                    width: 100px;
                    edited(text) => {AppState.mandantennummer = self.text}
                    horizontal-alignment: TextHorizontalAlignment.center;
                    placeholder-text: "Nummer";
                }

                Button {
                    clicked => {generate()}
                    text: "Weiter";
                }
            }
        }
        HorizontalLayout {
            spacing: 10px;
            visible: true;
            accessible-role: AccessibleRole.none;
            alignment: LayoutAlignment.stretch;
            padding: 10px;
            VerticalLayout {
                Text {
                    horizontal-alignment: TextHorizontalAlignment.center;
                    text: "PDFs";
                }
                VerticalLayout {
                    padding: 10px;
                    ListView {
                        accessible-role: AccessibleRole.button;
                        for item in AppState.pdf-names: Rectangle {
                            height: 40px;
                            HorizontalLayout {
                                alignment: LayoutAlignment.center;
                                Text { text: item.before; color: Colors.black; }

                               private property <color> c: item.partner ? Colors.green : Colors.blue;
                                Text { text: item.matched; color: c; font-weight: 700; }
                                Text { text: item.after; color: Colors.black; }
                            }
                        }
                    }

                }
            }

            Rectangle {
                width: 1px;
                background: #ccc;
            }
            VerticalLayout {
                Text {
                    horizontal-alignment: TextHorizontalAlignment.center;
                    text: "CSV";
                }
                VerticalLayout {
                    padding: 10px;
                    ListView  {
                        for item in AppState.csv-names: Rectangle {
                            height: 40px;
                            HorizontalLayout {
                                alignment: LayoutAlignment.center;
                                Text { text: item.before; color: Colors.black; }

                                private property <color> c: item.partner ? Colors.green : Colors.blue;
                                Text { text: item.matched; color: c; font-weight: 700; }
                                Text { text: item.after; color: Colors.black; }
                            }
                        }
                    }
                }
            }
        }
    }
}

component Loading inherits Rectangle {
    Spinner {
        indeterminate: true;
        width: 48px;
        height: 48px;
    }
}


component Finish inherits Rectangle {
    VerticalLayout {
        alignment: center;
        Text {
            text: "Die Importdateien wurden erfolgreich erstellt!";
            font-size: 24pt;
            horizontal-alignment: center;
        }
        Text {
            text: "Du kannst dieses Fenster jetzt schließen :)";
            font-size: 12pt;
            horizontal-alignment: center;
        }
        HorizontalBox {
            padding-top: 100px;
            VerticalLayout {
                Text {
                    font-size: 12pt;
                    text: "Buchungssätze: ";
                    horizontal-alignment: center;
                }
                Text {
                    font-size: 12pt;
                    text: "PDFs:";
                    horizontal-alignment: center;
                }
                Text {
                    font-size: 12pt;
                    font-weight: FontWeight.extra-bold;
                    text: "Beleglinks:";
                    horizontal-alignment: center;
                }
            }
            VerticalLayout {
                Text {
                    font-size: 12pt;
                    text: AppState.total_buchungssaetze;
                    horizontal-alignment: center;
                }
                 Text {
                    font-size: 12pt;
                    text: AppState.total_pdfs;
                    horizontal-alignment: center;
                }
                Text {
                    font-size: 12pt;
                    text: AppState.linked;
                    font-weight: FontWeight.extra-bold;
                    horizontal-alignment: center;
                }
            }
        }
    }
}


export component ConfirmDialog inherits Dialog {
    title: @tr("Profil löschen");
    callback confirm();
    callback abort();

    Text {
      text: "Bist du sicher, dass du dieses Profil löschen möchtest?";
    }
    StandardButton {
        kind: ok;
        clicked => {
            confirm();
        }
    }
    StandardButton {
        kind: cancel;
        clicked => {abort()}
    }
}

export component AppWindow inherits Window {
    preferred-height: 500px;
    preferred-width: 800px;
    min-height: 500px;
    min-width: 800px;
    callback request-pdf-dir();
    callback request-csv-file();
    callback generate();
    callback get-names();
    callback filter(string);
    callback change_profiles_location();
    callback update_name(string);
    callback delete_profile();
    callback update_ids(string);

    title: @tr("Simba Importbearbeitung");

    if AppState.current-view == 0: FileSelect {
        request-pdf-dir => { root.request-pdf-dir(); }
        request-csv-file => { root.request-csv-file(); }
        get_names => { root.get-names(); }
        change_profiles_location => {root.change_profiles_location()}
        delete_profile => {root.delete_profile()}
    }

    if AppState.current-view == 1: ChooseNamespace{
        filter(text) => { root.filter(text); }
        update_name(text) => {root.update_name(text)}
        generate() => {
            generate();
        }
        update_ids(text) => {root.update_ids(text)}
    }
    if AppState.current-view == 2: Loading {}
    if AppState.current-view == 3: Finish {}
}

